import { Inter } from "next/font/google";
import "./globals.css";
import {ClerkProvider} from "@clerk/nextjs";
import { Suspense } from "react";
import Loading from "./loading";
import CommonLayout from "@/components/common-layout";
import { Toaster } from "@/components/ui/toaster";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
      <ClerkProvider>
        <html lang="en">
        <body>
          <Suspense fallback={<Loading/>}><CommonLayout children={children}/></Suspense>
          <Toaster/>
        </body>
      </html>
      </ClerkProvider>
  );
}
